packages:
  - 'apps/*'
  - 'packages/*'
ignoredBuiltDependencies:
  - esbuild
  - sharp
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - oxc-resolver
  - sharp
  - supabase
